CREATE DATABASE NOTAS;
USE NOTAS;

CREATE TABLE NT_PROFESSORA(
    PRO_ID INTEGER NOT NULL AUTO_INCREMENT,
    PRO_NOME VARCHAR(70) NOT NULL,
    PRO_EMAIL VARCHAR(70)  NOT NULL UNIQUE,
    CONSTRAINT PRO_PK PRIMARY KEY (PRO_ID)
);

CREATE TABLE NT_MEDIAS(
    ME_ID INTEGER NOT NULL AUTO_INCREMENT,
    ME_NOME VARCHAR(70) NOT NULL,
    ME_PRO_ID INTEGER NOT NULL,
    ME_NOTA VARCHAR(3) NOT NULL,
    CONSTRAINT ME_PK PRIMARY KEY (ME_ID),
    CONSTRAINT ME_PRO_FK FOREIGN KEY (ME_PRO_ID) REFERENCES NT_PROFESSORA(PRO_ID)
);